name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Next.js App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: "pnpm"

      - name: Enable Corepack
        run: corepack enable

      - name: Setup pnpm
        run: corepack prepare pnpm@8.15.5 --activate

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm build
